// app/mispeedo/page.tsx
import { AppCtaSection } from "@/components/apps/app-cta-section";
import {
  AppFeaturesSection,
  Feature,
} from "@/components/apps/app-features-section";
import { AppHeaderSection } from "@/components/apps/app-header-section";
import { Gauge, Palette, SlidersHorizontal, Zap } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MiSpeedo | Set2Pass",
  description:
    "MiSpeedo is an intuitive app developed by Set2Pass Driving School, designed to keep you informed about your speed, course, and distance while you drive.",
};

const features: Feature[] = [
  {
    Icon: Gauge,
    title: "Introducing MiSpeedo",
    description:
      "MiSpeedo is an intuitive app developed by Set2Pass Driving School, designed to keep you informed about your speed in various units while you drive. It also offers essential details about your direction (course) and diligently tracks the total distance you cover on your journey.",
  },
  {
    Icon: Palette,
    title: "Customise",
    description:
      "With MiSpeedo, you'll always stay on track with accurate address information, regularly updated every 10 seconds. Plus, you have the freedom to customise the app's display colour theme to your liking, ensuring a personalised and enjoyable experience.",
  },
  {
    Icon: SlidersHorizontal,
    title: "Calibrate",
    description:
      "Fine-tune the GPS speed displayed by the app to match your vehicle's speedometer. This is useful because many vehicle speedometers show a slightly faster speed than your actual travel speed. With MiSpeedo's calibration, you'll have the confidence of knowing your displayed speed aligns with your vehicle's performance.",
  },
  {
    Icon: Zap,
    title: "Easy to Use",
    description:
      "Whether you're on a road trip or just commuting, MiSpeedo is the reliable driving companion that keeps you informed, safe, and in control throughout your journey. Enjoy a smoother, more informed ride with MiSpeedo!",
  },
];

const appStoreLink = "https://apps.apple.com/app/mispeedo/id1498459907";

export default function MiSpeedoPage() {
  return (
    <main>
      <AppHeaderSection
        title="MiSpeedo"
        description="An intuitive speedometer app developed by Set2Pass Driving School. Track your speed, direction, and distance — all in one place."
        appStoreLink={appStoreLink}
        img="/images/mispeedo.webp"
        altText="MiSpeedo app showing a digital speedometer on an iPhone"
      />

      <AppFeaturesSection
        title="Your Reliable Driving Companion"
        description=" Stay informed about your speed, direction, and distance with accurate GPS tracking and a customisable display."
        features={features}
        dense={false}
      />

      <AppCtaSection
        title="Track your speed with confidence"
        description="Download MiSpeedo from the App Store and enjoy a smoother, more informed ride."
        appStoreLink={appStoreLink}
        buttonText="Get MiSpeedo"
        privacyPolicyLink="/mispeedo/privacy-policy"
      />
    </main>
  );
}

// pages/mispeedo/index.vue
<script setup lang="ts">
import AppShowcasePage, {
  type AppIcon,
  type Feature,
} from "~/components/AppShowcasePage.vue";

const features: Feature[] = [
  {
    title: "Introducing MiSpeedo",
    imageUrl: "/img/mispeedo-0.webp",
    body: [
      "MiSpeedo is an intuitive app developed by SET2PASS Driving School, designed to keep you informed about your speed in various units while you drive.",
      "But it doesn't stop there! This handy tool goes the extra mile by offering essential details about the direction you're heading, known as 'course,' and diligently tracking the total distance you cover on your journey.",
    ],
  },
  {
    title: "Customize",
    imageUrl: "/img/mispeedo-2.webp",
    body: [
      "With MiSpeedo, you'll always stay on track with accurate address information, regularly updated every 10 seconds.",
      "Plus, you have the freedom to customize the app's display color theme to your liking, ensuring a personalized and enjoyable experience.",
    ],
  },
  {
    title: "Calibrate",
    imageUrl: "/img/mispeedo-1.webp",
    body: [
      "One of the standout features of MiSpeedo is its calibration capability. You can fine-tune the GPS speed displayed by the app to match your vehicle's speedometer.",
      "This adjustment is useful because many vehicle speedometers show a slightly faster speed than your actual travel speed.",
      "With MiSpeedo's calibration, you'll have the confidence of knowing your displayed speed aligns with your vehicle's performance.",
    ],
  },
  {
    title: "Easy to Use",
    imageUrl: "/img/mispeedo-3.webp",
    body: [
      "Whether you're on a road trip or just commuting, MiSpeedo is the reliable driving companion that keeps you informed, safe, and in control throughout your journey.",
      "Enjoy a smoother, more informed ride with MiSpeedo!.",
    ],
  },
];

const appIcons: AppIcon[] = [
  {
    href: "https://apps.apple.com/gb/app/mispeedo/id1498459907",
    imageUrl: "/img/mispeedo-ios.webp",
    text: "MiSpeedo",
  },
];
</script>

<template>
  <app-showcase-page
    header-image-src="/img/mispeedo-1.webp"
    :features="features"
    page-title="MiSpeedo | Set2Pass"
    :app-icons="appIcons"
    description="MiSpeedo is an intuitive app developed by SET2PASS Driving School, designed to keep you informed about your speed in various units while you drive."
    noun="MiSpeedo"
    app-section-title="Find MiSpeedo on the App Store"
  />
</template>
