// pages/driveclass/privacy-policy.vue
<script setup lang="ts">
useMetadata({
  title: "DriveClass Privacy Policy | Set2Pass",
  description: "DriveClass privacy policy",
});
</script>

<template>
  <text-page title="Privacy Policy" class="mb-12">
    <p>
      DriveClass (“the Service”) collects and uses information only to provide
      and improve the app. By using the Service, you agree to this policy.
    </p>

    <p class="font-weight-bold">Permissions</p>

    <p>
      Location: Needed to display your position on the map. Location data is
      stored only in saved track files on your device.
    </p>

    <p class="font-weight-bold">Data Collection and Sharing</p>
    <p>
      All location information stays on your device. The Service does not use
      the Internet or cookies, and does not share data with third parties.
    </p>

    <p class="font-weight-bold">Security</p>

    <p>
      Personal information is only stored in saved track files. These files are
      not encrypted. If you choose to share them, be aware that no transmission
      method is completely secure.
    </p>
  </text-page>
</template>

// app/driveclass/privacy-policy/page.tsx
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { Terms, TermSection } from "@/components/terms";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Set2Pass",
  description:
    "Privacy Policy for Set2Pass Driving School, covering data collection, usage, and protection.",
};

const sections: TermSection[] = [
  {
    title: "Permissions",
    items: [
      "Location: Needed to display your position on the map. Location data is stored only in saved track files on your device.",
    ],
  },
  {
    title: "Data Collection and Sharing",
    items: [
      "All location information stays on your device. The Service does not use the Internet or cookies, and does not share data with third parties.",
    ],
  },
  {
    title: "Security",
    items: [
      "Personal information is only stored in saved track files. These files are not encrypted. If you choose to share them, be aware that no transmission method is completely secure.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main>
      <Navbar />

      <Terms
        title="Privacy Policy"
        subtitle="DriveClass (“the Service”) collects and uses information only to provide and improve the app. By using the Service, you agree to this policy."
        sections={sections}
      />

      <Footer />
    </main>
  );
}
