// components/home/contact.tsx
import { Card } from "@/components/common/card";
import { Section } from "@/components/common/section";
import { Button } from "@/components/ui/button";
import { Facebook, Mail, Phone } from "lucide-react";

export function Contact() {
  return (
    <Section id="contact" muted>
      <Card className="bg-primary p-10 text-center md:p-16">
        <h2
          className="text-balance text-3xl font-bold tracking-tight text-primary-foreground md:text-4xl"
          style={{ fontFamily: "var(--font-heading)" }}
        >
          Ready to start your driving journey?
        </h2>
        <p className="mx-auto mt-4 max-w-xl text-primary-foreground/80">
          Get in touch today to join our waiting list. We offer automatic
          lessons with Nikki and manual lessons with Sean.
        </p>

        <div className="mt-8 flex flex-col items-center justify-center gap-4 w-64 mx-auto">
          <Button
            asChild
            size="lg"
            variant="secondary"
            className="h-12 rounded-full px-8 text-base w-full"
          >
            <a href="https://www.facebook.com/Set2Pass" target="_blank">
              <Facebook className="size-4" />
              Message us on Facebook
            </a>
          </Button>
          <Button
            asChild
            size="lg"
            variant="outline"
            className="h-12 rounded-full border-primary-foreground/30 bg-transparent px-8 text-base text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground w-full"
          >
            <a href="tel:+447719997000">
              <Phone className="size-4" />
              Call Us
            </a>
          </Button>
          <Button
            asChild
            size="lg"
            variant="outline"
            className="h-12 rounded-full border-primary-foreground/30 bg-transparent px-8 text-base text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground w-full"
          >
            <a href="mailto:set2pass@outlook.com">
              <Mail className="size-4" />
              Email Us
            </a>
          </Button>
        </div>
      </Card>
    </Section>
  );
}

// pages/contact.vue
<script setup lang="ts">
useMetadata({
  title: "Contact | Set2Pass",
  description: "Contact us today to enquire about driving lessons",
});
</script>

<template>
  <hero-base color="background" class="py-12">
    <div class="d-flex justify-center">
      <icon-card
        icon-url="/icon/speech-bubble-icon.svg"
        title="Lessons & Enquiries"
      >
        <a class="section" href="https://facebook.com/Set2Pass" target="_blank">
          <img
            src="/icon/facebook-icon.svg"
            style="width: 33px"
            class="Facebook Icon"
          />
          <div class="section-body">
            <span class="font-weight-bold">Facebook</span>
            <span class="font-weight-light">Message us on Facebook</span>
          </div>
        </a>
        <a class="section" href="tel:07719997000">
          <v-icon style="" size="x-large">mdi-phone</v-icon>
          <div class="section-body">
            <div class="section-body">
              <span class="font-weight-bold">Phone</span>
              <span class="font-weight-light">0771 999 7000</span>
            </div>
          </div>
        </a>
        <a class="section" href="mailto:set2pass@outlook.com">
          <v-icon style="" size="x-large">mdi-email</v-icon>
          <div class="section-body">
            <span class="font-weight-bold">Email</span>
            <span class="font-weight-light">set2pass@outlook.com</span>
          </div>
        </a>
      </icon-card>
    </div>
  </hero-base>
</template>

<style scoped>
.section {
  display: flex;
  align-items: center;
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 4px;
  padding: 1rem;
  gap: 1rem;
  text-decoration: none;
  color: inherit;
  height: 75px;
}

@media (hover: hover) {
  .section:hover {
    background: rgba(0, 0, 0, 0.1);
  }
}

.section-body {
  display: flex;
  flex-direction: column;
}
</style>
